/**
 * Notion MCP Wrapper
 *
 * Provides methods for creating pages and databases in Notion via MCP.
 * Falls back to returning markdown content for manual creation when
 * the MCP server is unavailable.
 */

import { callTool, isServerAvailable } from './client';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface NotionPageResult {
  id: string;
  url: string;
  isMock: boolean;
  fallbackMarkdown?: string;
  warning?: string;
}

export interface NotionDatabaseResult {
  id: string;
  url: string;
  isMock: boolean;
  fallbackMarkdown?: string;
  warning?: string;
}

export interface NotionProperty {
  name: string;
  type: 'title' | 'rich_text' | 'number' | 'select' | 'multi_select' | 'date' | 'url' | 'email' | 'checkbox';
  options?: string[];
}

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

const NOTION_MCP_URL = process.env.NOTION_MCP_URL ?? 'http://localhost:3103';

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Create a page in Notion.
 *
 * @param title     Page title
 * @param content   Page content (markdown)
 * @param parentId  Optional parent page or database ID
 */
export async function createPage(
  title: string,
  content: string,
  parentId?: string,
): Promise<NotionPageResult> {
  try {
    const available = await isServerAvailable(NOTION_MCP_URL, { timeoutMs: 3000 });
    if (!available) {
      return buildFallbackPage(title, content, parentId);
    }

    const params: Record<string, unknown> = { title, content };
    if (parentId) {
      params.parentId = parentId;
    }

    const result = await callTool(
      NOTION_MCP_URL,
      'notion_create_page',
      params,
      { timeoutMs: 10_000 },
    );

    if (result.isError) {
      console.warn(`[mcp/notion] createPage error: ${result.errorMessage}`);
      return buildFallbackPage(title, content, parentId);
    }

    const data = result.content as Record<string, unknown>;
    return {
      id: String(data.id ?? 'unknown'),
      url: String(data.url ?? ''),
      isMock: false,
    };
  } catch (err) {
    console.warn('[mcp/notion] createPage exception:', err);
    return buildFallbackPage(title, content, parentId);
  }
}

/**
 * Create a database in Notion.
 *
 * @param title      Database title
 * @param properties Array of property definitions
 * @param parentId   Optional parent page ID
 */
export async function createDatabase(
  title: string,
  properties: NotionProperty[],
  parentId?: string,
): Promise<NotionDatabaseResult> {
  try {
    const available = await isServerAvailable(NOTION_MCP_URL, { timeoutMs: 3000 });
    if (!available) {
      return buildFallbackDatabase(title, properties);
    }

    const params: Record<string, unknown> = { title, properties };
    if (parentId) {
      params.parentId = parentId;
    }

    const result = await callTool(
      NOTION_MCP_URL,
      'notion_create_database',
      params,
      { timeoutMs: 10_000 },
    );

    if (result.isError) {
      console.warn(`[mcp/notion] createDatabase error: ${result.errorMessage}`);
      return buildFallbackDatabase(title, properties);
    }

    const data = result.content as Record<string, unknown>;
    return {
      id: String(data.id ?? 'unknown'),
      url: String(data.url ?? ''),
      isMock: false,
    };
  } catch (err) {
    console.warn('[mcp/notion] createDatabase exception:', err);
    return buildFallbackDatabase(title, properties);
  }
}

// ---------------------------------------------------------------------------
// Fallback Builders
// ---------------------------------------------------------------------------

function buildFallbackPage(
  title: string,
  content: string,
  parentId?: string,
): NotionPageResult {
  const fallbackMarkdown = [
    `# ${title}`,
    '',
    parentId ? `> Parent: ${parentId}` : '',
    '',
    content,
    '',
    '---',
    '*This page was generated by Tideworks Agent Office. Create it manually in Notion.*',
  ]
    .filter(Boolean)
    .join('\n');

  return {
    id: `mock-${Date.now()}`,
    url: '',
    isMock: true,
    fallbackMarkdown,
    warning: 'Notion MCP server unavailable. Markdown content ready for manual creation.',
  };
}

function buildFallbackDatabase(
  title: string,
  properties: NotionProperty[],
): NotionDatabaseResult {
  const propertyLines = properties.map((p) => {
    const optionsStr = p.options?.length ? ` (options: ${p.options.join(', ')})` : '';
    return `| ${p.name} | ${p.type}${optionsStr} |`;
  });

  const fallbackMarkdown = [
    `# Database: ${title}`,
    '',
    '## Properties',
    '| Name | Type |',
    '|------|------|',
    ...propertyLines,
    '',
    '---',
    '*This database was generated by Tideworks Agent Office. Create it manually in Notion.*',
  ].join('\n');

  return {
    id: `mock-${Date.now()}`,
    url: '',
    isMock: true,
    fallbackMarkdown,
    warning: 'Notion MCP server unavailable. Database schema ready for manual creation.',
  };
}
